### ISSUE TITLE
Fix failing generation of Fluid view helper documentations

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3-Documentation/t3docs-ci-deploy#4]
The generation of the Fluid view helper documentation [fails](https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/workflows/fluid-viewhelper.yml) for TYPO3 `main` and `11.5` whereas it succeeds for `10.4`. Make it run again for all 3 TYPO3 branches.

**Comment by alexander-nitsche** [comment]
I could identify two reasons for the failures:

(1) The dependency injection fails when creating the ImageService object in the [ImageViewHelper](https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/fluid/Classes/ViewHelpers/ImageViewHelper.php#L103) with this error:
```
/t3docs-ci-deploy/core (11.5)*$ ./bin/generateschema TYPO3\\\CMS\\\Backend > ../schemas/typo3/backend/latest/schema.xsd
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function TYPO3\CMS\Extbase\Service\ImageService::__construct(), 0 passed in /t3docs-ci-deploy/core/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3199 and exactly 1 expected in /t3docs-ci-deploy/core/typo3/sysext/extbase/Classes/Service/ImageService.php:48
Stack trace:
#0 /t3docs-ci-deploy/core/typo3/sysext/core/Classes/Utility/GeneralUtility.php(3199): TYPO3\CMS\Extbase\Service\ImageService->__construct()
#1 /t3docs-ci-deploy/core/typo3/sysext/fluid/Classes/ViewHelpers/ImageViewHelper.php(103): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance()
#2 /t3docs-ci-deploy/core/vendor/typo3/fluid-schema-generator/src/SchemaGenerator.php(46): TYPO3\CMS\Fluid\ViewHelpers\ImageViewHelper->__construct()
#3 /t3docs-ci-deploy/core/vendor/typo3/fluid-schema-generator/s in /t3docs-ci-deploy/core/typo3/sysext/extbase/Classes/Service/ImageService.php on line 48
```
which is probably due to a missing boot of dependency injection in this context. This can be confirmed by replacing
```
$generator = new \TYPO3\FluidSchemaGenerator\SchemaGenerator();
```
with
```
\TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_CLI);
\TYPO3\CMS\Core\Core\Bootstrap::init($autoloader, true);

$generator = new \TYPO3\FluidSchemaGenerator\SchemaGenerator();
```
in https://github.com/TYPO3/Fluid.SchemaGenerator/blob/master/bin/generateschema#L48, which lets the run succeed - at least for `11.5`.

(2) The generation of view helper schema in TYPO3 `main` also fails because it requires PHP >= 8.1.0 whereas the current GitHub workflows use PHP 7.4.

**Comment by alexander-nitsche** [comment]
The recent patches of [Fluid Schema Generator](https://github.com/TYPO3/Fluid.SchemaGenerator) have fixed the DI problem of (1). 

Missing is (2).

**Comment by alexander-nitsche** [comment]
(2) is solved with the recent patches of this repository (e.g. PRs #7 and #8). The Fluid ViewHelper documentation succeeds for TYPO3 10.4, 11.5 and 12-dev, see https://github.com/TYPO3-Documentation/t3docs-ci-deploy/actions/workflows/fluid-viewhelper.yml.

Thanks @lolli42 for fixing the Fluid schema generator.
